# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, '3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
      with:
          python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pdm install

    - name: Install nltk punkt
      run: python3 -m nltk.downloader punkt

    - name: Test with pytest and coverage
      run: pdm run pytest

    - name: Codecov
      uses: codecov/codecov-action@v4.5.0

